[build-system]
requires = ["jupyter_packaging~=0.10,<2", "jupyterlab>=4.0.0a25"]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.options]
skip-if-exists = ["jupytercad/labextension/static/style.js"]
ensured-targets = ["jupytercad/labextension/static/style.js", "jupytercad/labextension/package.json"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.check-manifest]
ignore = ["jupytercad/labextension/**", "yarn.lock", ".*", "package-lock.json"]
