[build-system]
build-backend = "jupyter_packaging.build_api"
requires = ["jupyter_packaging~=0.10,<2", "jupyterlab>=4.0.0a25"]

[tool.jupyter-packaging.options]
ensured-targets = ["jupytercad/labextension/static/style.js", "jupytercad/labextension/package.json"]
skip-if-exists = ["jupytercad/labextension/static/style.js"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.check-manifest]
ignore = [
  "jupytercad/labextension/**",
  "yarn.lock",
  ".*",
  "package-lock.json",
  "src/_interface/**",
  "examples/**",
  "*.webpack.config.js",
  "schema.js",
]
